<HomeScreen>:
    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            title: "my weather"


        MDBoxLayout:
            padding: "20sp"
            spacing: "20sp"
            MDTextField:
                hint_text: "Введіть місто"
                mode: "fill"
            MDIconButton:
                icon: "magnify"
                md_bg_color: "#602b7a"


        MDLabel:
            text: "Content"
            halign: "center"



